const base = {
  nordNight0: '#2e3440',
  nordNight2: '#434c5e',
  nordNight3: '#4c566a',
  snowStorm0: '#d8dee9',
  nordNight1: '#3b4252',
  snowStorm1: '#e5e9f0',
  snowStorm2: '#eceff4',
  frost0: '#8fbcbb',
  frost1: '#88c0d0',
  frost2: '#81a1c1',
  frost3: '#5e81ac',
  aurora0: '#bf616a',
  aurora1: '#d08770',
  aurora2: '#ebcb8b',
  aurora3: '#a3be8c',
  aurora4: '#b48ead',
}

export const lightTheme = {
  ...base,
  mode: 'light',
  BLACK: 'black',
  WHITE: 'white',
  LIGHT_GREY: '#D1D5DB',
  GREY: '#4B5563',
  DARK_GREY: '#202937',
  FACEBOOK: '#3B5998',
  FLIPPING_BG_COLOR: '#E5E7EB',
  PRIMARY_BG_COLOR: 'white',
  PRIMARY_TEXT_COLOR: 'black',
  PRIMARY_BUTTON_COLOR: base.frost3,
  PRIMARY_BUTTON_TEXT_COLOR: 'white',
  FADED_GREY: '#4B5563',
  LOADING_CIRCLE_COLOR: 'green',
  OVERLAY_BG_COLOR: '#4B5563',
  FADED_TEXT_COLOR: base.nordNight2,
}

export const darkTheme = {
  ...lightTheme,
  mode: 'dark',
  FACEBOOK: '#3B5998',
  FLIPPING_BG_COLOR: '#374151',
  PRIMARY_BG_COLOR: '#4c566a',
  PRIMARY_TEXT_COLOR: 'white',
  PRIMARY_BUTTON_COLOR: base.frost2,
  PRIMARY_BUTTON_TEXT_COLOR: 'white',
  FADED_GREY: '#D1D5DB',
  FADED_TEXT_COLOR: base.snowStorm0,
}
