const base = {
  nordNight0: '#2e3440',
  nordNight1: '#3b4252',
  nordNight2: '#434c5e',
  nordNight3: '#4c566a',
  snowStorm0: '#d8dee9',
  snowStorm1: '#e5e9f0',
  snowStorm2: '#eceff4',
  frost0: '#8fbcbb',
  frost1: '#88c0d0',
  frost2: '#81a1c1',
  frost3: '#5e81ac',
  aurora0: '#bf616a',
  aurora1: '#d08770',
  aurora2: '#ebcb8b',
  aurora3: '#a3be8c',
  aurora4: '#b48ead',
}

export const lightTheme = {
  ...base,
  mode: 'light',
  BLACK: 'black',
  WHITE: 'white',
  LIGHT_GREY: 'lightgrey',
  GREY: 'darkgrey',
  DARK_GREY: 'darkgrey',
  FACEBOOK: '#3B5998',
  PRIMARY_BG_COLOR: 'white',
  PRIMARY_TEXT_COLOR: 'black',
  PRIMARY_BUTTON_COLOR: base.frost3,
  PRIMARY_BUTTON_TEXT_COLOR: 'white',
  FADED_GREY: 'grey',
}

export const darkTheme = {
  ...base,
  mode: 'dark',
  BLACK: 'black',
  WHITE: 'white',
  LIGHT_GREY: 'lightgrey',
  DARK_GREY: 'darkgrey',
  GREY: 'lightgrey',
  FACEBOOK: '#3B5998',
  PRIMARY_BG_COLOR: '#4c566a',
  PRIMARY_TEXT_COLOR: 'white',
  PRIMARY_BUTTON_COLOR: base.frost2,
  PRIMARY_BUTTON_TEXT_COLOR: 'white',
  FADED_GREY: 'lightgrey',
}
